run:
  timeout: 5m
  skip-dirs:
    - server_test

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    # - contextcheck -> need investigation
    - depguard
    - durationcheck
    # - exhaustive -> need investigation
    - exportloopref
    - forbidigo
    - gocritic
    - gocheckcompilerdirectives
    - gosec
    - makezero
    - nilerr
    - nolintlint
    - reassign
    - sqlclosecheck
    - unconvert

linters-settings:
  nolintlint:
    require-explanation: true
    require-specific: true

  gocritic:
    disabled-checks:
      - ifElseChain       # style
      - singleCaseSwitch  # style & it's actually not a bad idea to use single case switch in some cases
      - assignOp          # style
      - commentFormatting # style

  depguard:
    # Kind of list is passed in.
    # Allowed values: allowlist|denylist
    # Default: denylist
    list-type: denylist

    # Check the list against standard lib.
    # Default: false
    include-go-root: false

    # A list of packages for the list type specified.
    # Can accept both string prefixes and string glob patterns.
    # Default: []
    packages:
      - go.temporal.io/sdk/log

    # A list of packages for the list type specified.
    # Specify an error message to output when a denied package is used.
    # Default: []
    packages-with-error-message:
      - go.temporal.io/sdk/log: do not use Temporal log package directly, use the SPC log package instead

