name: Test - Integration
on:
  push:
    tags:
      - v*
    branches:
      - main
      - "v*"
  workflow_dispatch:
  pull_request:


jobs:
  golangci:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Flowpipe repository
        uses: actions/checkout@v3
        with:
          path: flowpipe

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false # setup-go v4 caches by default, do not change this parameter, check golangci-lint-action doc: https://github.com/golangci/golangci-lint-action/pull/704

      - name: Run tests
        run: make integration-test
        working-directory: flowpipe